Add plotting docs
richardreeve/Phylo.jl pull request #64
Opened 2021-10-11 17:11 UTC by mkborregaard

Here I've added my first pass at docs for plotting. Notice this is made onto my previous branch.

2021-10-12 21:22 UTC, richardreeve requested changes
Looks good. A couple of minor edits.

2021-10-12 21:22 UTC, richardreeve commented on docs/src/man/plotting.md
> +It adds these keywords to the ones initiallysupported by Plots.jl:
```suggestion
It adds these keywords to the ones initially supported by Plots.jl:
```

2021-10-12 21:22 UTC, richardreeve commented on docs/src/man/plotting.md
> +- tipfont: a tuple defining the font to use for leaf names (default is `(7,))
I'm assuming `(7,)` is a meaningful font?! It might be useful to add a link to how to describe fonts if so...
```suggestion
- tipfont: a tuple defining the font to use for leaf names (default is `(7,)`)
```

2021-10-12 21:22 UTC, richardreeve commented on docs/src/man/plotting.md
> +ENV["GKSwstype"]="nul" # hide
It might be nice to add a comment explaining this line. I'm sure it's obvious to someone who knows Plots.jl, but it looks like madness to an outsider!

2021-10-12 21:22 UTC, richardreeve commented on docs/src/man/plotting.md
> +To demonstrate, let' start by defining a custom function for evolving a trait
```suggestion
To demonstrate, let's start by defining a custom function for evolving a trait
```

2021-10-12 21:22 UTC, richardreeve commented on docs/src/man/plotting.md
> +on the phylogeny accoding to Brownian motion, using the utility funciton
```suggestion
on the phylogeny according to Brownian motion, using the utility function 
```

2021-10-12 21:22 UTC, richardreeve commented on docs/src/man/plotting.md
> +nodes or branches within the phylogeny
```suggestion
nodes or branches within the phylogeny.
```

2021-10-12 21:37 UTC, richardreeve commented on docs/src/man/plotting.md
> +hummers = open(parsenewick, "../../../test/hummingbirds.tree")
```suggestion
hummers = open(parsenewick, Phylo.path("hummingbirds.tree")
```

2021-10-13 19:11 UTC, mkborregaard commented on docs/src/man/plotting.md
> +ENV["GKSwstype"]="nul" # hide
It will be hidden in the docs - that´s what the `# hide` comment does, it's an operator to Documenter.

2021-10-13 19:23 UTC, mkborregaard commented
should be good to go - I've added all your suggestions except the one about the env

2021-10-13 19:45 UTC, richardreeve approved these changes

2021-10-13 19:48 UTC, richardreeve commented
I guess the errors in 1.4 are a result of the parental branch, so good to merge here.

2021-10-14 13:16 UTC, merged